package com.example.recyclerviewuse.util

object SampleData {
    val data = listOf(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Aliquam eget nisi eget orci molestie porttitor.",
        "Pellentesque pretium nunc ac justo ultricies convallis.",
        "Maecenas tristique urna quis posuere rhoncus.",
        "Morbi vel lorem feugiat, viverra dui sed, ullamcorper quam.",
        "Pellentesque laoreet eros a augue mollis, vel elementum urna condimentum.",
        "Praesent lobortis enim in gravida tempor.",
        "Nullam ut neque nec leo bibendum condimentum vel non lacus.",
        "Maecenas eu ligula convallis quam convallis pretium.",
        "Morbi sed neque eget ante laoreet faucibus.",
        "Nunc vel enim consectetur, laoreet ligula id, vulputate nunc.",
        "Morbi aliquam quam in magna pellentesque, in consectetur lorem convallis.",
        "Pellentesque sed nisl id ex tincidunt porttitor vitae in ipsum.",
        "Quisque laoreet sem dignissim nunc gravida sodales.",
        "Donec convallis purus gravida, hendrerit purus quis, placerat mauris.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Aliquam eget nisi eget orci molestie porttitor.",
        "Pellentesque pretium nunc ac justo ultricies convallis.",
        "Maecenas tristique urna quis posuere rhoncus.",
        "Morbi vel lorem feugiat, viverra dui sed, ullamcorper quam.",
        "Pellentesque laoreet eros a augue mollis, vel elementum urna condimentum.",
        "Praesent lobortis enim in gravida tempor.",
        "Nullam ut neque nec leo bibendum condimentum vel non lacus.",
        "Maecenas eu ligula convallis quam convallis pretium.",
        "Morbi sed neque eget ante laoreet faucibus.",
        "Nunc vel enim consectetur, laoreet ligula id, vulputate nunc.",
        "Morbi aliquam quam in magna pellentesque, in consectetur lorem convallis.",
        "Pellentesque sed nisl id ex tincidunt porttitor vitae in ipsum.",
        "Quisque laoreet sem dignissim nunc gravida sodales.",
        "Donec convallis purus gravida, hendrerit purus quis, placerat mauris.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Aliquam eget nisi eget orci molestie porttitor.",
        "Pellentesque pretium nunc ac justo ultricies convallis.",
        "Maecenas tristique urna quis posuere rhoncus.",
        "Morbi vel lorem feugiat, viverra dui sed, ullamcorper quam.",
        "Pellentesque laoreet eros a augue mollis, vel elementum urna condimentum.",
        "Praesent lobortis enim in gravida tempor.",
        "Nullam ut neque nec leo bibendum condimentum vel non lacus.",
        "Maecenas eu ligula convallis quam convallis pretium.",
        "Morbi sed neque eget ante laoreet faucibus.",
        "Nunc vel enim consectetur, laoreet ligula id, vulputate nunc.",
        "Morbi aliquam quam in magna pellentesque, in consectetur lorem convallis.",
        "Pellentesque sed nisl id ex tincidunt porttitor vitae in ipsum.",
        "Quisque laoreet sem dignissim nunc gravida sodales.",
        "Donec convallis purus gravida, hendrerit purus quis, placerat mauris.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Aliquam eget nisi eget orci molestie porttitor.",
        "Pellentesque pretium nunc ac justo ultricies convallis.",
        "Maecenas tristique urna quis posuere rhoncus.",
        "Morbi vel lorem feugiat, viverra dui sed, ullamcorper quam.",
        "Pellentesque laoreet eros a augue mollis, vel elementum urna condimentum.",
        "Praesent lobortis enim in gravida tempor.",
        "Nullam ut neque nec leo bibendum condimentum vel non lacus.",
        "Maecenas eu ligula convallis quam convallis pretium.",
        "Morbi sed neque eget ante laoreet faucibus.",
        "Nunc vel enim consectetur, laoreet ligula id, vulputate nunc.",
        "Morbi aliquam quam in magna pellentesque, in consectetur lorem convallis.",
        "Pellentesque sed nisl id ex tincidunt porttitor vitae in ipsum.",
        "Quisque laoreet sem dignissim nunc gravida sodales.",
        "Donec convallis purus gravida, hendrerit purus quis, placerat mauris.",
    )
}